<?php

function views_row_view_mode_views_api() {
  return array(
    'api' => 3,
    'template path' => drupal_get_path('module', 'views_row_view_mode'),
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function views_row_view_mode_preprocess_node(&$variables) {
  if (isset($variables['view']->style_plugin) && get_class($variables['view']->style_plugin) == 'views_plugin_style_views_row_view_mode') {
    $every_string = explode(',', $variables['view']->style_plugin->options['every_row_numbers']);

    foreach ($every_string as $last_of_row) {
      if (is_int($variables['view']->row_index / $last_of_row) && $variables['view']->row_index != 0) {
        $variables['classes_array'][] = 'every-' . $last_of_row;
      }
    }
  }
}
